[build]
  base = "react-portfolio"
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/mobile/*"
  to = "/mobile/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
